-- V5: Envers audit history was never migrated. On fresh Postgres the app boots
-- with ddl-auto: validate, and validation fails because the revinfo / *_aud
-- tables the @Audited mappings expect do not exist (H2's create-drop hid this).
-- This migration creates them, carries the acting user on every revision, and
-- relaxes patients.birthdate so the anonymization path (GDPR Art 17 retention)
-- can fully scrub identifying data.

CREATE TABLE revinfo (
    -- AuditRevisionEntity maps the revision-number property as `id`; ddl-auto: validate
    -- fails without this exact column name (Envers' REV default only applies to its own entity).
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT,
    actor VARCHAR(255)
);

CREATE TABLE patients_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT NOT NULL,
    name VARCHAR(255),
    birthdate DATE,
    diagnosis VARCHAR(255),
    notes VARCHAR(2048),
    assigned_clinician VARCHAR(255),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_patients_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(id)
);

CREATE TABLE consent_records_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT NOT NULL,
    patient_id BIGINT,
    consent_type VARCHAR(255),
    granted BOOLEAN,
    status SMALLINT,
    source VARCHAR(255),
    created_at TIMESTAMPTZ,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_consent_records_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(id)
);

CREATE TABLE consult_notes_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT NOT NULL,
    patient_id BIGINT,
    provider_name VARCHAR(255),
    note_text VARCHAR(4096),
    created_at TIMESTAMPTZ,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_consult_notes_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(id)
);

CREATE TABLE audit_entries_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT NOT NULL,
    actor VARCHAR(255),
    action VARCHAR(255),
    entity_type VARCHAR(255),
    entity_id BIGINT,
    details VARCHAR(4096),
    created_at TIMESTAMPTZ,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_audit_entries_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(id)
);

-- Anonymized retention keeps the clinical record but scrubs identifiers;
-- birthdate must be nullable for that.
ALTER TABLE patients ALTER COLUMN birthdate DROP NOT NULL;

-- The hand-written V1 column used TEXT but the entity maps notes to
-- varchar(2048); ddl-auto: validate does not treat TEXT as compatible.
ALTER TABLE patients ALTER COLUMN notes TYPE VARCHAR(2048);
